apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer # works across namespaces, Issuer only in one namespace
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: julian.strosahl@efs-auto.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux